Espressive/cascara

.github/labeler.yml
=> Fix the syntax for labeler

.vscode/settings.json, design/framer/esp-fds.framerfx/package.json, package.json, tokens.config.json, tokens/color/base.json, tokens/color/font.json, tokens/size/font.json, yarn.lock
Should take care of #41 
Generates design tokens in our build folder for now so they stay out of version control.
=> Design Token support

Makefile, TODO.md
=> add Makefile with common commands

docs/package.json, docs/public/robots.txt, netlify.toml, yarn.lock
Updating a few missing items for the docs. We may want to add a build process for the docs to CI at some point to make sure these things getting broken does not happen in between builds.
=> Update dependencies for docs, add robots.txt

docs/src/lib/MDX_COMPONENTS.js, package.json, packages/cascara/src/index.js, packages/cascara/src/lib/JsonDisplay/JsonDisplay.doc.mdx, packages/cascara/src/lib/JsonDisplay/JsonDisplay.fixture.js, packages/cascara/src/lib/JsonDisplay/JsonDisplay.js, packages/cascara/src/lib/JsonDisplay/JsonDisplay.module.scss, packages/cascara/src/lib/JsonDisplay/index.js, packages/cascara/src/lib/customPropTypes/README.md, packages/cascara/src/lib/customPropTypes/index.js, packages/cascara/src/lib/customPropTypes/json.js, yarn.lock
=> json display component

docs/src/components/Nav/Nav.js, docs/src/components/Nav/Nav.module.scss, docs/src/components/Nav/NavItem.js, docs/src/components/PropTable/PropTable.js, docs/src/components/PropTable/PropTable.module.scss, docs/src/components/Tag/Tag.js, docs/src/components/Tag/Tag.module.scss, docs/src/components/Tag/index.js, docs/src/components/index.js, docs/src/lib/getMDXDirFiles.js, docs/src/lib/getMDXTree.js, docs/src/styles/_app.scss, packages/cascara/src/layouts/TableLayout/TableLayout.spec.mdx, packages/cascara/src/modules/DataBoolean/Boolean.spec.mdx, packages/cascara/src/structures/Admin/0-Admin.doc.mdx, packages/cascara/src/ui/Checkbox/Checkbox.Spec.mdx, packages/cascara/src/ui/Pagination/0-Pagination.doc.mdx, packages/cascara/src/ui/Pagination/1-Pagination.spec.mdx
- Adds metadata to navigation for status from first MDX file if present
- Cleans up PropTable to display even with some incomplete type info
- Updates existing MDX docs to show a prop table and current component state
This should make some of our work much more visible and easier to see progress. Additionally, once the opening sections are done with concepts, it will be easier to see where some of these components should actually live.
=> Update lots of doc stuff

packages/cascara/src/ui/Form/poc/FormPublicAPI.fixture.js, packages/cascara/src/ui/Table/TableStyleTest.module.scss
This is just a fixture that explores a public API for forms that is very similar to the public API for table in terms of configuring modules.
=> Form Public API Exploration

packages/cascara/src/modules/AllModules.fixture.js, packages/cascara/src/modules/DataCheckbox/DataCheckbox.js, packages/cascara/src/modules/DataEmail/DataEmail.js, packages/cascara/src/modules/DataModule.module.scss, packages/cascara/src/modules/DataNumber/DataNumber.js, packages/cascara/src/modules/DataRadio/DataRadio.js, packages/cascara/src/modules/DataSelect/DataSelect.js, packages/cascara/src/modules/DataText/DataText.js, packages/cascara/src/modules/DataTextArea/DataTextArea.js, utils/eslint-config-espressive/src/jsx-a11y.js
=> FDS-16 MVP: Data Modules

packages/cascara/src/ui/Dashboard/data/BarDevice.json, packages/cascara/src/ui/Dashboard/poc/DashboardPAC.fixture.js
Minor changes :) 
added counter, rearranged horizontal stacked bar chart most-least
=> Design review changes

.circleci/config.yml
Updates our Slack notification messages from CircleCI
=> FDS-130 slack circleci orb update

packages/cascara/src/ui/Form/Form.doc.mdx
Hi team,
This adds PAC docs for Form. cheers!
=> FDS-29 - Form PAC documentation

.github/workflows/autosquash.yml
Resolves FDS-152
This should make our PRs automatically squash against develop when other PRs get merged.
=> chore(FDS-152): Set up autosquash

packages/cascara/src/structures/AdminStructure/AdminStructureHeader.js, packages/cascara/src/ui/Chat/ChatAttachment.js, packages/cascara/src/ui/Dashboard/widgets/WidgetBar.js
Resolves FDS-179.
More prop type fixes, this time for: AdminStructureHeader, ChatAttachment and WidgetBar.
=> chore(FDS-179): [Chat, Structures] fix prop type warnings

.changeset/neat-days-serve.md, packages/cascara/src/lib/getStatusFromDataLength.js, packages/cascara/src/ui/Form/Form.js, yarn.lock
Add optional chaining for getting length on dataDisplay object keys in Form
This is a hotfix going directly to main
=> hotfix(FDS-352): Fix bug in Form

.changeset/wild-monkeys-fix.md, packages/cascara/src/private/Popover/Popover.fixture.js, packages/cascara/src/private/Popover/Popover.js, packages/cascara/src/structures/AdminStructure/components/Drawer/Drawer.js, packages/cascara/src/structures/AdminStructure/components/Drawer/Drawer.module.scss, packages/cascara/src/structures/AdminStructure/components/Header/Header.js, packages/cascara/src/structures/AdminStructure/components/Nav/Nav.js, packages/cascara/src/structures/AdminStructure/components/Nav/Nav.module.scss, packages/cascara/src/structures/AdminStructure/components/Nav/NavLink.js, packages/cascara/src/ui/ActionStack/ButtonStack.js, packages/cascara/src/ui/ActionStack/DropdownStackItem.js, yarn.lock
fix(FDS-368) Nav descenders getting cut off
fix(FDS-366) More permissive prop types on Nav slot component for linkComponent with older routers
fix(FDS-370) Aria role on Popper with fallback
fix(FDS-369) Update ActionStack for handler
=> Nov Patches

.changeset/gold-peaches-begin.md, packages/cascara/src/ui/Dashboard/widgets/WidgetBar.js, packages/cascara/src/ui/Dashboard/widgets/WidgetBubble.js, packages/cascara/src/ui/Dashboard/widgets/WidgetPie.js, packages/cascara/src/ui/Dashboard/widgets/widgetConfig.js
Update the existing color theme to remove/replace any colors that might incorrectly communicate meaning (range, risk, positive, negative)
=> feat(FDS-313): [Cascara] - Update the existing color theme for Dashboard

.github/PULL_REQUEST_TEMPLATE.md
Resolves [FDS-398](https://espressive.atlassian.net/browse/FDS-398).
Update PR checklist to require conventional commits.
=> chore(FDS-398): [Github] - update PR checklist, add conventional commits

.changeset/shy-poets-flow.md, packages/cascara/src/modules/DataCheckbox/DataCheckbox.fixture.js, packages/cascara/src/modules/DataCheckbox/DataCheckbox.js, packages/cascara/src/modules/DataCheckbox/DataCheckbox.test.js, packages/cascara/src/modules/DataCheckbox/DataCheckbox.test.snap
Improve unit test for the checkbox.
This component already had a unit test, I just added the format we have for the others for consistency, as well as accessibility labels
=> chore(FDS-35): [Tests]: Improve unit test for checkbox

.changeset/lucky-dolphins-pull.md, .danger/index.ts
Validate if the target branch requires the release branch.
=> chore(FDS-401): [Danger.js] - Validate if target branch requires release branch

.changeset/empty-parrots-arrive.md, packages/cascara/src/modules/ActionButton/ActionButton.test.js
Create unit test for ActionButton.
=> chore(FDS-255):[ActionButton]: Unit test for ActionButton

.changeset/gentle-actors-deliver.md, packages/cascara/src/modules/DataText/DataText.fixture.js, packages/cascara/src/modules/DataText/DataText.js, packages/cascara/src/modules/DataText/DataText.test.js, packages/cascara/src/modules/DataText/DataText.test.snap, packages/cascara/src/ui/FormOld/tests/Form.test.snap, packages/cascara/src/ui/TableOld/tests/TableSnapshot.test.snap
Improve unit test for input text.
This component already had a unit test, I just added the format we have for the others for consistency, as well as accessibility labels.
Update snapshot adding the text class and labels for accessibility
=> chore(FDS-38):[Tests]: Improve unit test for input text

.changeset/tame-lobsters-obey.md, .circleci/config.yml, docs/package.json, package.json, utils/eslint-config/package.json
Update node engine version to 14.18.2
Update node version to the most recent version.
=> chore(FDS-399):[Node]: Update node engine version to 14.18.2

README.md
Update README to use node version 14.18.2
=> chore(FDS-430):[Readme]: Update README file to use node version 14.18.2

.github/CODEOWNERS
=> chore(Codeowners): set odiseo42 as code owner for brians sections

.danger/index.ts
=> bugfix(FDS-433):[Danger]: Run danger when base and target branch is not develop or main

.danger/index.ts
This updates the config for **_Danger.js_** so it skips the checks on PRs that satisfy the following scenarios:
- develop -> main
- main -> develop
> More info [here](https://github.com/Espressive/cascara/pull/286#pullrequestreview-778762168).
=> chore(FDS-141): [Danger.js] - Do not run Danger checks in develop -> main and main -> develop PRs

ADR/typescript.md, package.json, yarn.lock
Version: 4.6.2
Date: 2022-03-04
> [Release notes](https://github.com/microsoft/TypeScript/releases/tag/v4.6.2).
- none
Snapshots updated due to aun update in dependencies.
Dependencies updated due to bump in library versions.
=> chore(FDS-498) [Monorepo] - update typescript

ADR/prettier.md, package.json, yarn.lock
This bumps prettier to its most recent version v2.5.1.
`package.json` file updated because of the version bump.
=> chore(FDS-489): [Monorepo] - bump prettier to v2.5.1

ADR/eslint.md
We are not updating ESLint and its ecosystem until we can move forward with React and friends.
=> chore(FDS-478): [Monorepo] - update eslint

.changeset/fifty-dolls-wait.md, packages/cascara/src/atoms/TimePicker/TimePicker.js
Update version for Date and Time pickers
=> feat(FDS-519): [Changeset] Update version for Date and Time pickers

.changeset/kind-tools-beam.md, packages/cascara/src/components/Table/0-Table.mdx, packages/cascara/src/components/Table/Table.js, packages/cascara/src/components/Table/TableBase.js, packages/cascara/src/components/Table/TableHeader.js, packages/cascara/src/components/Table/__propTypes.js, packages/cascara/src/components/Table/atoms/SortableHeader.js, packages/cascara/src/components/Table/fixtures/Sorting.fixture.js, packages/cascara/src/components/Table/index.js, packages/cascara/src/components/Table/state/sortingReducer.js, packages/cascara/src/components/Table/state/useTableSortState.js, packages/cascara/src/index.js
Fixtures changed to leverage the new `sortState` prop.
=> feat(FDS-521): [Table] expose sort state

.changeset/few-tigers-knock.md, packages/cascara/src/atoms/DatePicker/DatePicker.js
=> Release - April 12
