- src/layout/admin/src/Admin.js
- src/layout/admin/src/cosmos.decorator.js
- src/layout/admin/src/index.js
- src/ui/README.md
- src/ui/button/src/Button.fixture.js
- src/ui/button/src/cosmos.decorator.js
- src/ui/pagination/src/cosmos.decorator.js
Cannot set this at the root due to JSX. This is also because of our webpack config relying on CRA.
We will need to add this in the /src folder for each component for now. We still inherit the other fixture globals.
> Strict mode works for fixtures

- .circleci/config.yml
- packages/cascara/package.json
No new components. This PR updates the Circle CI build configuration to make sure we are also testing the docs to confirm they are not broken between each PR. As of now, we would only be able to tell if the docs are broken when we go to merge to the main branch and find that the build has failed at that stage.
Build phases are now:
1. install
2. lint, test
3. build cosmos, docs, cascara
The build stages are not published anywhere. They are just intended to have the build phases run and if anything is broken, the builds will fail and alert us.
> resolves #77 add docs to CI, adjust build phases

- docs/src/components/Main/Main.js
- docs/src/components/Main/index.js
- docs/src/components/Nav/Nav.js
- docs/src/components/Nav/Nav.module.css
- docs/src/components/index.js
- docs/src/lib/mdxUtils.js
- docs/src/pages/[slug].js
- docs/src/pages/_app.js
- docs/src/pages/docs/[[...mdx]].js
- docs/src/pages/index.js
- packages/cascara/pages/getting-started.mdx
- packages/cascara/pages/index.mdx
- packages/cascara/pages/public-api-components.mdx
- packages/cascara/src/ui/Button/Button.doc.mdx
> Docs now support index and principles section

- packages/cascara/src/modules/ActionEdit/ActionEdit.js
- packages/cascara/src/ui/Table/0-Table.mdx
Hi team,
The action name for the`edit` module was being reported as `actionName`, which is incorrect, the correct term is `name`. Also, the documentation was improved to be more clear in terms of how to use Actions.
cheers
> DEV-13327 - fix Table action name is not reported correctly by onAction

- utils/legacy-css/src/css/semantic.min.css
All Semantic UI inputs that were `transparent` had a previously customized padding to match the padding to the labels which we removed in the last update. This PR removes that custom padding, restoring the original lack of left padding on transparent inputs to make these inputs align with the label.
> FDS-92 Remove the now incorrect left padding inside transparent inputs

- packages/cascara/src/modules/ActionEdit/ActionEdit.js
- packages/cascara/src/modules/DataCheckbox/DataCheckbox.js
The checkbox module in `display` mode was using the `isChecked` value from its `local state`, which is incorrect. The value to  `display` should always come from the actual data,  as it is the only source of truth.
This PR fixes the bug by implementing the `useCheckboxState` hook for the checkbox' state as well as other minor changes.
During our pair-programing session we discovered some other issues which we'll address in future PRs, once the relevant tasks are created.
> FDS-91 - Fix checkbox not resetting to the original value if canceled

- package.json
- packages/cascara/src/modules/ActionButton/ActionButton.js
- packages/cascara/src/modules/DataCheckbox/DataCheckbox.js
- packages/cascara/src/modules/DataEmail/DataEmail.js
- packages/cascara/src/modules/DataNumber/DataNumber.js
- packages/cascara/src/modules/DataRadio/DataRadio.js
- packages/cascara/src/modules/DataSelect/DataSelect.js
- packages/cascara/src/modules/DataText/DataText.js
- packages/cascara/src/modules/DataTextArea/DataTextArea.js
- packages/cascara/src/modules/ModuleError/ModuleError.js
- packages/cascara/src/ui/Table/Table.test.js
- packages/cascara/src/ui/Table/Table.test.snap
- packages/cascara/src/ui/Table/TableRow.js
- yarn.lock
The **getAttributeValueFromRecord** function was acting as a _field accessor_ for the modules, this is not what we want.
This PR, if merged, will remove this unnecessary accessor function. The _value_ is now provided to the module as a _prop_ when Table cells are created. The test suite has also been improved, adding a test case to effectively validate any changes in the record.
cheers
> FDS-94 - Remove the getAttributeValueFromRecord function from modules

- .circleci/config.yml
- docs/package.json
Hi team, 
We are bumping Next to its latest release. This build will probably fail because we still need to merge [FDS-76 - use the correct version of nodejs for vercel (12.x)](https://github.com/Espressive/cascara/pull/133) for Vercel to pick the new config up.
Cheers
> FDS-77 - Bump Next to the latest version

- packages/cascara/src/modules/ActionEdit/ActionEdit.js
- packages/cascara/src/ui/Table/context/RowProvider.js
- packages/cascara/src/ui/Table/context/TableProvider.js
Hi team,
As of today, all reccords in a Table can be edited at the same time, which causes lots of issues. The root cause seems to be that the `isEditing` flag is scoped to the row, so every row is in charge of its edit state.
**The bug**
https://recordit.co/U8HRrG52bJ
The flag was replaced with the actual id of the record that is being edited, we also moved the flag and its setter functions to the upper `context`.
**The fix**
https://recordit.co/J6b3d6NLCj
I am sure there could be other ways to implement this, please feel free to propose any other approach.
Cheers.
> FDS-95 - Prevent multiple rows from entering in edit mode

- packages/cascara/src/ui/Dashboard/Dashboard.module.scss
- packages/cascara/src/ui/Dashboard/poc/DashboardPAC.fixture.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetStats.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetStatsStat.js
- [NA] Includes unit tests for _ALL_ required FDS use cases
- [NA] Includes an explanation for any changes to Jest snapshots (should be a PR tag automatically added if this happens)
It also adds an icon to stat cards if they are clickable to make them more easily discoverable to users. No API changes needed for end users.
> FDS-119 Focus styles to Stat Widget

- .circleci/config.yml
Hi team,
This disables the CI step that builds the docs.
> FDS-98 - Disable the CI step that builds the docs

- packages/cascara/src/ui/Form/Form.js
- packages/cascara/src/ui/Form/Form.test.js
- packages/cascara/src/ui/Form/Form.test.snap
Hi team,
These are the tests for Form. Cheers!
> FDS-30 - unit tests for form

- packages/cascara/src/ui/ActionsMenu/ActionsMenu.js
- packages/cascara/src/ui/Popover/Popover.fixture.js
- packages/cascara/src/ui/Table/Table.test.snap
We should now not have to worry about z-index from parent defined z-index and we will also not have a lot of extra portals sitting in the DOM.
This patch will need to be tested once published to verify.
Updating Snapshot test due to the Menu no longer rendering in a portal, but instead now rendering adjacent to the menu button
> FDS-136 Do not render popover as a modal

- packages/cascara/src/modules/ActionButton/ActionButton.js
- packages/cascara/src/ui/ActionsMenu/ActionsMenu.js
- packages/cascara/src/ui/Button/Button.js
- packages/cascara/src/ui/Table/fixtures/ActionStack.Table..fixture.js
Hi team,
This PR adds the logic to use the action `name` if no `content` is specified.
Snapshots are updated beccause the `content` || `name` changes reflected in DOM elements.
> FDS-137 - use action name for button name if no content is specified

- packages/cascara/src/ui/ActionsMenu/ActionsMenu.js
- packages/cascara/src/ui/ActionsMenu/ActionsMenu.module.scss
- packages/cascara/src/ui/Table/Table.test.snap
- packages/cascara/src/ui/Table/fixtures/ActionStack.Table.fixture.js
Snapshot tests are being updated here because the menu is no longer being rendered inline. There would technically be no way to break out of the positioning here with the popper due to the sticky cell position.
Note that these snapshot tests are not actually showing the menu as it is being rendered in a portal. Something for us to think about in the future.
> FDS-138 Return ActionsMenu to portal rendering, and set z-index

- packages/cascara/src/ui/ActionsMenu/ActionsMenu.js
This ends up breaking the `onAction` handler logic that relies on the DOM element having a `name` attribute.
- `name` is now kept in `...rest` so it reaches the DOM.
- `actionName` is defensively mutted before rendering the menu item
> fix(ActionsMenu): not passing 'name' prop down to the DOM element

- packages/cascara/src/lib/mock/fakeData.js
- packages/cascara/src/ui/ActionsMenu/ActionsMenu.js
- packages/cascara/src/ui/Table/0-Table.mdx
- packages/cascara/src/ui/Table/Table.js
- packages/cascara/src/ui/Table/TableRow.js
- packages/cascara/src/ui/Table/fixtures/Conditional.Actions.fixture.js
Hi team,
This is a PoC on how we could handle `conditional actions` for Table.
This would add to Table:
- an `opt-in` prop `resolveRecordActions`. A function that receives 1) the current record and 2) the list of actions defined for the table; and returns the set of actions for that specific record.
- the minimal changes to make this work without making breaking changes
1. `yarn cosmos`
2. visit `Conditional actions` fixture
> feat(Table): Conditional actions

- packages/cascara/src/fixtures/ReactMemo.fixture.js
Resolves FDS-155
This fixture should show what happens when we have a handler function that is not wrapped with `useCallback` and how that impacts the use of `React.memo`.
We might actually want to create a collection of fixtures like this to share with the FE team. Hmm…
> chore(FDS-155): React.memo and useCallback example

- .circleci/config.yml
- lerna.json
- package.json
This new release step should only run on the `main` branch. I think it is safe to have the docs publish through the Vercel integration since we are basically building the docs on _every_ PR. They might land before the publishing actually happens. It is possible we might want to move the publishing up so that we can use any incremented version numbers to show up in the docs.
We are updating publish scripts so they can be reused in CircleCI config
> chore(FDS-159) Auto publish packages with Lerna from `main` and prerelease from `develop`

- packages/cascara/src/ui/Chat/ChatProvider.js
- packages/cascara/src/ui/Dashboard/widgets/Widget.js
- packages/cascara/src/ui/Form/context/FormProvider.js
- packages/cascara/src/ui/Pagination/Pagination.js
- packages/cascara/src/ui/Popover/Popover.js
- packages/cascara/src/ui/Section/Section.js
- packages/cascara/src/ui/Table/context/RowContext.js
- packages/cascara/src/ui/Table/context/RowProvider.js
- packages/cascara/src/ui/Table/context/TableContext.js
- packages/cascara/src/ui/Table/context/TableProvider.js
Fixes FDS-160
When working on FDS-147, we mistakenly used `element` prop type instead of `node`, which cause lots of warnings in the console.
> fix(fds-160): use node instead of element in prop types

- packages/cascara/src/ui/Dashboard/widgets/WidgetStatsStat.js
Resolves [FDS-179](https://espressive.atlassian.net/browse/FDS-179).
We made a mistake when setting prop types for `WidgetStatsStat`, we used `oneOf` isntead of `oneOfType`.
> chore(FDS-179): Dashboard, fix prop type warnings

- docs/package.json
- package.json
- packages/cascara/package.json
- packages/cascara/src/ui/Dashboard/data/PieChannel.json
- yarn.lock
This PR should resolve some lockfile issues that were present and causing issues in our CI install. It also should give us a warning-free installation, which we want to pass along to our consumers.
- This bumps all Nivo packages to 0.67.0
- We also alias `react-spring` to `@react-spring/web` since Nivo uses it, but the full platform flavor throws warnings about missing platform dependencies, which we do not support. Making sure we are only using the web platform package gets rid of those warnings for our package consumers.
> chore(FDS-182) Nivo version bump

- packages/cascara/package.json
Resolves FDS-206.
Design tokens was listed as `peer-dependency` for `Cascara`, which is incorrect. This PR removes such dependency.
> Chore/fds-206 remove design tokens as peer-dependency from Cascara

- docs/package.json
- package.json
- packages/cascara/package.json
- packages/cascara/src/structures/AdminStructure/AdminStructure.fixture.js
- packages/cascara/src/structures/AdminStructure/AdminStructure.js
- packages/cascara/src/structures/AdminStructure/AdminStructure.module.scss
- packages/cascara/src/structures/AdminStructure/components/Header/Header.module.scss
- packages/cascara/src/structures/hooks/index.js
- packages/cascara/src/structures/hooks/useThemeCustomProperties.js
- yarn.lock
There is now a `theme` prop available on `AdminStructure` which accepts an object. Typing is as follows:
```
theme: pt.shape({
color: pt.shape({
primary: pt.string,
secondary: pt.string,
}),
}),
```
This is intentionally generic so that we have an object that is flexible enough to extend if we find a need to add further theme support in the future. Make special note that `primary` and `secondary` are not at the root of the theme object but rather they are part of a `color` object like `color.primary` and `color.secondary`.
We the following two libraries for color processing and checking contrast ratios for accessibility:
- `color`
- `color-string`
> feat(FDS-207): Structure theme object support

- .vscode/settings.json
- packages/cascara/src/index.js
- packages/cascara/src/modules/ActionButton/ActionButton.js
- packages/cascara/src/ui/Form/Form.js
- packages/cascara/src/ui/Form/Form.test.js
- packages/cascara/src/ui/Form/Form.test.snap
- packages/cascara/src/ui/Form/modules/ActionEdit/ActionEdit.js
- packages/cascara/src/ui/Form/modules/FormRow/FormRow.js
- packages/cascara/src/ui/Form/poc/Form.fixture.js
- packages/cascara/src/ui/Table/ActionBar.test.snap
- packages/cascara/src/ui/Table/Table.test.snap
Resolves FDS-253.
We are moving towards a clean set of props that can be used interchangeably between `Form` and `Table`.
Old props are stripped away and new props are defined and wired-up.
Index of Cascara was updated to include propTypes exports.
Form fixture has been updated to include new props.
The changes in props, plus the fact that we are defining `arial-labels` for `Action` buttons has caused fixtures to change.
> chore(FDS-253): separate out all of the elements of dataConfig and get rid of it

- packages/cascara/src/ui/Dashboard/DashboardDX.fixture.js
- packages/cascara/src/ui/Dashboard/widgets/Widget.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetBar.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetBubble.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetGeoMap.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetHeatMap.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetLine.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetList.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetPie.js
- packages/cascara/src/ui/Dashboard/widgets/WidgetStats.js
- packages/cascara/src/ui/Dashboard/widgets/dataState.js
This also cleans up the logic for when to display a component or not into the widget itself where we decide if we should even render children
> bugfix(FDS-279)  Make sure empty class only present for empty or loading widgets

- packages/cascara/src/ui/Table/0-Table.mdx
- packages/cascara/src/ui/Table/TableBase.js
Resolves [FDS-284](https://espressive.atlassian.net/browse/FDS-284).
References: [DEV-15895](https://espressive.atlassian.net/browse/DEV-15895).
The [auto-uniqueIdAttribute-inference logic](https://github.com/Espressive/cascara/compare/develop...fix/FDS-284?expand=1#diff-a1b1889e48abb6e2ea0bdd7401e5f17dbefc252290534b4ce626bbc6e6f09abaR14) in TableBase returns `undefined` given the following sircumstances:
- a faulty check that always returns `true`, forcing the [auto-uniqueIdAttribute-inference logic](https://github.com/Espressive/cascara/compare/develop...fix/FDS-284?expand=1#diff-a1b1889e48abb6e2ea0bdd7401e5f17dbefc252290534b4ce626bbc6e6f09abaR14) to always kick-in.
- the `data` prop having a `uniqueIdAttribute` that is not  listed in …
> Fix TableBase: uniqueIdAttribute is incorrectly set to undefined by a faulty check

- packages/cascara/src/placeholders/JsonPlaceholder/JsonPlaceholder.fixture.js
- packages/cascara/src/placeholders/JsonPlaceholder/JsonPlaceholder.js
- [-] Includes unit tests for _ALL_ required FDS use cases
- [-] Does not mute any top level API props in React
- [-] Includes an explanation for any changes to Jest snapshots (should be a PR tag automatically added if this happens)
- [-] Component uses `React.forwardRef()` when a single DOM node is returned, _AND_ it makes React-sense to access that DOM node
Snapshots
Default:
Loading:
EmptyArray and EmptyObject:
Style:
Title:
> chore(FDS-311): Add empty and loading status to JSONPlaceholder

- .changeset/gentle-olives-talk.md
- packages/cascara/src/ui/Form/Form.doc.mdx.DISABLED
- packages/cascara/src/ui/Form/Form.js
Resolves FDS-346.
`resolveAllowedActions` does not align with the current implementation of `Form`, hence it's being removed.
> chore(FDS-346): [Cascara Form] - remove resolveAllowedActions prop from form

- .changeset/neat-days-serve.md
- .changeset/quick-glasses-look.md
- packages/cascara/src/lib/getStatusFromDataLength.js
- packages/cascara/src/ui/Form/Form.fixture.js
- packages/cascara/src/ui/Form/Form.js
- yarn.lock
Form was looking at the dataDisplay value for determining if it was empty or not, instead of the data prop
> hotfix(FDS-352): Update logic for empty/loading in Form

- .changeset/empty-melons-serve.md
- packages/cascara/src/structures/AdminStructure/AdminStructure.module.scss
- yarn.lock
Adds CSS support for the AdminStructure to work within the legacy Admin app
> Make AdminStructure compatible with legacy

- .changeset/nervous-poets-attack.md
- packages/cascara/src/structures/AdminStructure/AdminStructure.module.scss
- packages/cascara/src/structures/AdminStructure/components/Nav/Nav.module.scss
- yarn.lock
This is a patch fix to address two small CSS issues with the AdminStructure in both Safari and Firefox. Related tickets are linked to the FDS ticket.
> fix(FDS-379) Fix cross browser issues with Structure Nav/Header

- .changeset/shaggy-suits-begin.md
- .cosmos/config.json
- packages/cascara/styles/_scroll.scss
- yarn.lock
This resolves an issue in our scroll mixin within Cascara where we did not have an overflow setting for scroll that Firefox could use, so we did not have any scrolling at all.
If using Cosmos, this fixture can be used locally to validate scrolling is now working in Cosmos. http://localhost:4000/_renderer.html?_fixtureId=%7B%22path%22%3A%22packages%2Fcascara%2Fsrc%2Fstructures%2FAdminStructure%2FAdminStructure.fixture.js%22%2C%22name%22%3A%22no-drawer%22%7D
> fix(FDS-380) Firefox scroll working with fallback

- .changeset/smooth-steaks-sin.md
- packages/cascara/src/system-components/Boundaries/Boundaries.fixture.js
- packages/cascara/src/system-components/Boundaries/fallbacks/ErrorFallback.js
Improve default Boundaries FallbackComponent to only show the error message in the UI during development environments with support for showing them with a localstorage key.
Fixture for Boundaries updated with an error message.
> feat(FDS-371): [Cascara] - improve fallback component

- .changeset/fifty-moons-build.md
- .changeset/short-rabbits-joke.md
- docs/src/lib/MDX_COMPONENTS.js
- packages/cascara/src/ui/Columns/Columns.fixture.js
- packages/cascara/src/ui/Columns/Columns.js
- packages/cascara/src/ui/Columns/Columns.mdx
- packages/cascara/src/ui/Columns/Columns.module.scss
- packages/cascara/src/ui/Columns/Columns.test.js
- packages/cascara/src/ui/Columns/Columns.test.snap
- packages/cascara/src/ui/Columns/__globals.js
- packages/cascara/src/ui/Columns/index.js
- packages/cascara/src/ui/index.js
Add a new component called Columns that when wrapped around children will cause those children to display in columns using CSS.
> this is NOT grid. 
Snapshots created for the new component.
Fixtures created for the new component.
> feat(DEV-373):  [Cascara] - Columns component mvp

- .changeset/soft-paws-fix.md
- packages/cascara/package.json
- rollup.config.js
Remove DEV_MODE suffix for production environment
Add production **production** name environment
> chore(FDS-93): [Build] - Remove DEV_MODE suffix for prod environment

- .changeset/great-chefs-judge.md
- .circleci/config.yml
- packages/cascara/package.json
- yarn.lock
Closes [FDS-427](https://espressive.atlassian.net/browse/FDS-427).
add `@espressive/prop-types` as peer-dep
> chore(FDS-427): [Cascara] - add @espressive/prop-types as peer-dep

- .danger/index.ts
Resolves FDS-444.
This changes Danger.js' configuration to identify release -> main PRs and bypass the check for dependencies and fixtures in Release PRs.
The following errors should not popup in the aforementioned case.
> chore(FDS-444): [Danger.js] - Do not check and fail for dependencies and fixtures in release PRs

- .changeset/rich-nails-guess.md
- packages/cascara/src/components/Dashboard/Dashboard.fixture.js
- packages/cascara/src/components/Dashboard/widgets/WidgetLine.js
Fixture of Dashboard changed to reflect WidgetLine's stacked prop implementation
> fix(FDS-515): [Dashboard] widget line does not implement stacked prop

- .changeset/brave-grapes-move.md
- packages/cascara/src/components/Table/Table.js
Currently, docgen does not have support importing propTypes from external locations. 
https://github.com/reactjs/react-docgen/issues/33
There is an external package named https://www.npmjs.com/package/react-docgen-external-proptypes-handler but does not have the full support, the proptype description appears as a custom without a clear reference:
Since this feature is not ready to be used, the propTypes for the table component has been moved to the owner component:
> chore(FDS-389):[Docs]: Fix propTypes for Table

- .changeset/real-trees-heal.md
- ADR/faker.md
Faker has been moved from a [personal github account](https://github.com/Marak/Faker.js#readme) to an [organization](https://github.com/faker-js), this change broke the history of the repository. There is no v6.6.6 as vscode suggests, [v6 is still in alpha](https://github.com/faker-js/faker/releases/tag/v6.0.0-alpha.7).
Faker is only used in Fixtures and tests, it is not a critical part of Cascara so we are sticking to our current versions. No updated dependencies.
> chore(FDS-484): [Monorepo] - update faker

- ADR/dotenv.md
This adds an ADR file to explain why we are staying in v8.2.0.
> chore(FDS-477): [Monorepo] create ADR for dotenv update

- .changeset/chilly-peas-tap.md
- packages/cascara/src/atoms/DatePicker/DatePicker.js
- packages/cascara/src/atoms/DatePicker/_globals.js
- packages/cascara/src/atoms/TimePicker/TimePicker.js
> bugfix(FDS-519): [Atoms] Fix typo in prop-types
